version: '3'
services:
  registry:
    build: ../../services/tools.descartes.teastore.registry
    expose:
      - "8080"
    ports:
      - "8081:8080"
  db:
    image: descartesresearch/teastore-db
    expose:
      - "3306"
    ports:
      - "3306:3306"
  persistence:
    build: ../../services/tools.descartes.teastore.persistence
    expose:
      - "8080"
    ports:
      - "8082:8080"
    environment:
      HOST_NAME: "persistence"
      REGISTRY_HOST: "registry"
      DB_HOST: "db"
      DB_PORT: "3306"
  auth:
    build: ../../services/tools.descartes.teastore.auth
    expose:
      - "8080"
    ports:
      - "8083:8080"
    environment:
      HOST_NAME: "auth"
      REGISTRY_HOST: "registry"
  image:
    build: ../../services/tools.descartes.teastore.image
    expose:
      - "8080"
    ports:
      - "8084:8080"
    environment:
      HOST_NAME: "image"
      REGISTRY_HOST: "registry"
  recommender:
    build: ../../services/tools.descartes.teastore.recommender
    expose:
      - "8080"
    ports:
      - "8085:8080"
    environment:
      HOST_NAME: "recommender"
      REGISTRY_HOST: "registry"
  webui:
    build: ../../services/tools.descartes.teastore.webui
    expose:
      - "8080"
    ports:
      - "8080:8080"
    environment:
      HOST_NAME: "webui"
      REGISTRY_HOST: "registry"
